-- DDL generated by Postico 2.1.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE designs (
    id SERIAL PRIMARY KEY,
    name character varying(255) NOT NULL,
    height_in_inches numeric NOT NULL,
    width_in_inches numeric NOT NULL,
    image_file_name character varying(1000) NOT NULL,
    design_created_by integer REFERENCES "user"(id) ON DELETE CASCADE,
    belongs_to_user integer REFERENCES "user"(id) ON DELETE CASCADE,
    inserted_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX designs_pkey ON designs(id int4_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER on_design_update
  BEFORE UPDATE ON public.designs
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at_to_now();

