-- DDL generated by Postico 2.1.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "user" (
    id SERIAL PRIMARY KEY,
    username character varying(80) NOT NULL UNIQUE,
    password character varying(1000) NOT NULL,
    inserted_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    access_level character varying(20) DEFAULT 'user'::character varying CHECK (access_level::text = ANY (ARRAY['user'::character varying, 'admin'::character varying]::text[]))
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_pkey ON "user"(id int4_ops);
CREATE UNIQUE INDEX user_username_key ON "user"(username text_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER on_user_update
  BEFORE UPDATE ON public."user"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at_to_now();

